version: "3"
services:
  db:
    image: postgres:11.5-alpine
    environment:
      POSTGRES_PASSWORD: 'TheP@ssw0rd12345'
      POSTGRES_USER: 'springuser'
      POSTGRES_DB: 'postgres'
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    driver: local
