version: '3'

services:
  db:
    image: mysql:8.0.27
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    # mbind: Operation not permitted というエラーが出る現象を回避
    cap_add:
      - SYS_NICE
