name: Deploy Azure Web Apps
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      cache:
        image: redis:6.0
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew build
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379

      - name: check results
        run: ls -l build/libs

      # - name: Azure WebApp
      #   uses: Azure/webapps-deploy@v2
      #   with:
      #     app-name: app-miyohide-javaapp
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #     package: build/libs/*.jar
