name: Deploy Azure Web Apps
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0.27
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: app_test
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew build

      - name: check results
        run: ls -l build/libs

      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: app-miyohide-javaapp
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: build/libs/*.jar
