name: Java CI with Gradle

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      cache:
        image: redis:6.0
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Build with Gradle
        run: ./gradlew build
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
      - name: save test log
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          path: ./build/reports
